// app/layout.jsx
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import { MusicProvider } from "../context/MusicContext";
import { UserProvider } from "../context/UserContext"



export const metadata = {
  title: "Mind-Pal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>

        <ThemeProvider> 
          <UserProvider>
          <MusicProvider>
            <div className=" ">{children}</div>
          </MusicProvider> 
          </UserProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
